name: Deploying to dev

on:
  push:
    branches:
      - main

jobs:
  deploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Write ssh key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ~/ssh_key \
            ubuntu@ec2-13-50-235-147.eu-north-1.compute.amazonaws.com << 'EOF'
            
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            export PATH="$HOME/.local/share/pnpm:$PATH"

            node -v
            pnpm -v

            cd test-deploy/
            git pull

            pnpm install
            pnpm run build

            pm2 restart docs
            pm2 restart web

          EOF
